if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )
cd yolov7

python detect.py --device 0 --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov7\yolov7\runs\train\exp4\weights\best.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 --save-txt
python detect.py --device 0 --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov7\yolov7\runs\train\exp5\weights\best.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 --save-txt
python detect.py --device 0 --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov7\yolov7\runs\train\exp6\weights\best.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 --save-txt
python detect.py --device 0 --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov7\yolov7\runs\train\exp7\weights\best.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 --save-txt
python detect.py --device 0 --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov7\yolov7\runs\train\exp8\weights\best.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 --save-txt
python detect.py --device 0 --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov7\yolov7\runs\train\exp9\weights\best.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 --save-txt
python detect.py --device 0 --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov7\yolov7\runs\train\exp10\weights\best.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 --save-txt