if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )
cd YOLOv6

python tools\infer.py --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov6\YOLOv6\runs\train\exp3\weights\best_ckpt.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 416 --save-txt
python tools\infer.py --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov6\YOLOv6\runs\train\exp4\weights\best_ckpt.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 416 --save-txt
python tools\infer.py --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov6\YOLOv6\runs\train\exp5\weights\best_ckpt.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 416 --save-txt
python tools\infer.py --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov6\YOLOv6\runs\train\exp6\weights\best_ckpt.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 416 --save-txt
python tools\infer.py --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov6\YOLOv6\runs\train\exp7\weights\best_ckpt.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 416 --save-txt
python tools\infer.py --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov6\YOLOv6\runs\train\exp8\weights\best_ckpt.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 416 --save-txt
python tools\infer.py --weights "C:\Users\Ari\Documents\scripts\xprize\models\image models\yolov6\YOLOv6\runs\train\exp9\weights\best_ckpt.pt" --iou-thres .25 --source "C:\Users\Ari\Documents\scripts\xprize\database files\image_splits\inat2017\100\images\val" --conf-thres 0.41 --img-size 416 416 --save-txt
